export const platformImages = [
  {
    emoji: '📊',
    src: '/images/analytics.png',
    alt: 'Carbon analytics dashboard',
    title: 'Analytics Dashboard',
    description: 'Track emissions trends, category breakdowns, and sustainability scores in one view. Feeds dynamic stats directly to the AI Coach.',
    successLabel: 'Tracking Status',
    successMetric: 'Active -15% Q2 Reduction',
    formula: 'Total CO₂e = Sum(Transport + Energy + Food + Waste)',
    benefits: ['Real-time trend charts', 'Personalized benchmarks', 'Category breakdowns'],
  },
  {
    emoji: '👣',
    src: '/images/carbon_footprint.png',
    alt: 'Carbon footprint visualization',
    title: 'Carbon Footprint',
    description: 'Understand your personal impact with clear, actionable footprint visualizations compared against national targets.',
    successLabel: 'Target Alignment',
    successMetric: 'Paris Agreement Met',
    formula: 'Eco Score = 100 - (Total Emissions / Offset Target) * 10',
    benefits: ['Paris Agreement mapping', 'Dynamic offset sandbox', 'Per-capita comparisons'],
  },
  {
    emoji: '🚗',
    src: '/images/sustainable_transporatation.png',
    alt: 'Sustainable transportation',
    title: 'Transport Analysis',
    description: 'Compare car, public transport, cycling, and EV usage with CO₂ estimates to optimize daily commuting paths.',
    successLabel: 'Commute Impact',
    successMetric: '$1,200 saved / year',
    formula: 'Emissions = Distance * Mode Factor (e.g., 0.12kg/km for compact)',
    benefits: ['Route comparison matrix', 'EV savings simulator', 'Active transit rewards'],
  },
  {
    emoji: '☀️',
    src: '/images/renewable_energy.png',
    alt: 'Renewable energy',
    title: 'Renewable Energy',
    description: 'Explore solar potential, green energy share, and electricity savings based on smart appliance conversions.',
    successLabel: 'Solar Efficiency',
    successMetric: '65% Grid Independence',
    formula: 'Solar Offset = Roof Area * Solar Radiation * Efficiency Factor',
    benefits: ['Roof space solar estimator', 'Smart appliance calculator', 'Clean heating savings'],
  },
  {
    emoji: '♻️',
    src: '/images/eco-friendly(trash bin).png',
    alt: 'Recycling tracker',
    title: 'Waste & Recycling',
    description: 'Monitor recycling habits, food waste reduction, and composting rates to minimize landfill methane emissions.',
    successLabel: 'Zero Waste Goal',
    successMetric: '90% Composting Rate',
    formula: 'Landfill Factor = Weight * Methane Potential (0.45kg CO₂e/kg)',
    benefits: ['Compost target tracking', 'Single-use plastic audit', 'Circular economy tips'],
  },
] as const;



