CREATE TABLE IF NOT EXISTS "User" (
  id TEXT PRIMARY KEY,
  "firebaseUid" TEXT NOT NULL UNIQUE,
  email TEXT UNIQUE,
  "displayName" TEXT,
  "avatarUrl" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "CarbonProfile" (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL UNIQUE REFERENCES "User"(id) ON DELETE CASCADE,
  "transportKmPerDay" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "bikeKmPerDay" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "publicTransportKmPerDay" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "evKmPerDay" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "monthlyKwh" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "renewableSharePercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "foodHabit" TEXT NOT NULL DEFAULT 'mixed',
  "recyclingFrequency" INTEGER NOT NULL DEFAULT 0,
  "plasticUsageScore" INTEGER NOT NULL DEFAULT 0,
  "domesticFlightsPerYear" INTEGER NOT NULL DEFAULT 0,
  "internationalFlightsPerYear" INTEGER NOT NULL DEFAULT 0,
  "sustainabilityScore" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
